apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: battleship
type: Opaque
stringData:
  POSTGRES_DB: battleship
  POSTGRES_USER: battleship
  POSTGRES_PASSWORD: battleship123
