apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: battleship
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'battleship-api'
        metrics_path: '/actuator/prometheus'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - battleship
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: battleship-api
            action: keep
          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: __address__
            replacement: '$1:8080'
